version: "3.9"

services:
  web:
    build: .
    ports:
      - "${PUBLIC_PORT}:${FLASK_RUN_PORT}"
    env_file:
      - .env
    environment:
      DB_HOST: db
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432" # <--- CHANGED THIS PORT
volumes:
  pgdata: